// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoke6Cv4LoXkoh1Y86UadSSe63oDxVeNI',
    appId: '1:925798475835:web:d5f9a7fd14f1f33118941e',
    messagingSenderId: '925798475835',
    projectId: 'travelapp-57409',
    authDomain: 'travelapp-57409.firebaseapp.com',
    storageBucket: 'travelapp-57409.firebasestorage.app',
    measurementId: 'G-ZH5DW5GQ23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNRrPBlqhXypjoeBId-s5ljUK7IISuPI',
    appId: '1:925798475835:android:51d997bcc9e6ffdc18941e',
    messagingSenderId: '925798475835',
    projectId: 'travelapp-57409',
    storageBucket: 'travelapp-57409.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOBrKGZmlMaNdXN_j54o0YF21-JQKEF8w',
    appId: '1:925798475835:ios:8ae749e2749a7c3c18941e',
    messagingSenderId: '925798475835',
    projectId: 'travelapp-57409',
    storageBucket: 'travelapp-57409.firebasestorage.app',
    iosBundleId: 'com.example.travelHotelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOBrKGZmlMaNdXN_j54o0YF21-JQKEF8w',
    appId: '1:925798475835:ios:8ae749e2749a7c3c18941e',
    messagingSenderId: '925798475835',
    projectId: 'travelapp-57409',
    storageBucket: 'travelapp-57409.firebasestorage.app',
    iosBundleId: 'com.example.travelHotelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoke6Cv4LoXkoh1Y86UadSSe63oDxVeNI',
    appId: '1:925798475835:web:ed1d2aefd16988d518941e',
    messagingSenderId: '925798475835',
    projectId: 'travelapp-57409',
    authDomain: 'travelapp-57409.firebaseapp.com',
    storageBucket: 'travelapp-57409.firebasestorage.app',
    measurementId: 'G-BLDTJH1S0Z',
  );
}

